#ifndef CAPTIVE_PORTAL_H
#define CAPTIVE_PORTAL_H

// Auto-generated from captive_portal.html - do not edit directly!
// Edit captive_portal.html and run: python html_to_header.py

static const char CAPTIVE_PORTAL_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"  <head>\n"
"    <title>Streak Tracker Setup</title>\n"
"    <meta charset=\"UTF-8\" />\n"
"    <meta\n"
"      name=\"viewport\"\n"
"      content=\"width=device-width, initial-scale=1.0, maximum-scale=1\"\n"
"    />\n"
"    <style>\n"
"      :root {\n"
"        --color-white: #ffffff;\n"
"        --color-black: #000000;\n"
"        --color-primary: #b22222;\n"
"        --color-primary-light: #ba4e4e;\n"
"        --color-error: #ff0000;\n"
"        --color-gray-100: #f8f9f9;\n"
"        --color-gray-200: #e3e5e8;\n"
"        --color-gray-300: #c7ccd1;\n"
"        --color-gray-400: #9099a4;\n"
"        --color-gray-500: #4f5660;\n"
"        --color-gray-600: #2e3338;\n"
"        --color-gray-700: #060607;\n"
"      }\n"
"      * {\n"
"        font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto,\n"
"          sans-serif;\n"
"        color: var(--color-gray-200);\n"
"        box-sizing: border-box;\n"
"      }\n"
"      body {\n"
"        touch-action: manipulation;\n"
"        background-color: var(--color-gray-700);\n"
"        margin: 0;\n"
"        padding: 2rem 1rem;\n"
"        display: flex;\n"
"        flex-direction: column;\n"
"        align-items: center;\n"
"        min-height: 100vh;\n"
"      }\n"
"      .header {\n"
"        text-align: center;\n"
"        margin-bottom: 1rem;\n"
"      }\n"
"      .header h2 {\n"
"        margin: 0.5rem 0 0.2rem 0;\n"
"      }\n"
"      .header h4 {\n"
"        margin: 0.2rem 0;\n"
"        opacity: 0.7;\n"
"        font-weight: normal;\n"
"      }\n"
"      .header p {\n"
"        opacity: 0.5;\n"
"        max-width: 90%;\n"
"        margin: 0.5rem auto;\n"
"        font-size: 0.9rem;\n"
"      }\n"
"      .card {\n"
"        background-color: var(--color-gray-600);\n"
"        box-shadow: 0 0.25rem 0.75rem rgba(0, 0, 0, 0.3);\n"
"        border-radius: 0.75rem;\n"
"        max-width: 400px;\n"
"        width: 100%;\n"
"        padding: 1.5rem;\n"
"      }\n"
"      h3 {\n"
"        margin: 0 0 1rem 0;\n"
"        text-align: center;\n"
"      }\n"
"      .network-list {\n"
"        max-height: 250px;\n"
"        overflow-y: auto;\n"
"        margin-bottom: 1rem;\n"
"        border: 1px solid var(--color-gray-500);\n"
"        border-radius: 0.5rem;\n"
"      }\n"
"      .network-item {\n"
"        display: flex;\n"
"        align-items: center;\n"
"        padding: 0.75rem 1rem;\n"
"        border-bottom: 1px solid var(--color-gray-500);\n"
"        cursor: pointer;\n"
"      }\n"
"      .network-item:last-child {\n"
"        border-bottom: none;\n"
"      }\n"
"      .network-item:hover {\n"
"        background-color: var(--color-gray-500);\n"
"      }\n"
"      .network-item.selected {\n"
"        background-color: var(--color-primary);\n"
"      }\n"
"      .network-item input[type=\"radio\"] {\n"
"        margin-right: 0.75rem;\n"
"        accent-color: var(--color-primary);\n"
"      }\n"
"      .network-name {\n"
"        flex: 1;\n"
"        font-size: 0.95rem;\n"
"      }\n"
"      .network-signal {\n"
"        opacity: 0.5;\n"
"        font-size: 0.8rem;\n"
"      }\n"
"      .form-group {\n"
"        margin-bottom: 1rem;\n"
"      }\n"
"      label {\n"
"        display: block;\n"
"        font-size: 0.85rem;\n"
"        margin-bottom: 0.25rem;\n"
"        opacity: 0.8;\n"
"      }\n"
"      input[type=\"text\"],\n"
"      input[type=\"password\"] {\n"
"        width: 100%;\n"
"        padding: 0.75rem;\n"
"        border: 1px solid var(--color-gray-500);\n"
"        border-radius: 0.5rem;\n"
"        font-size: 1rem;\n"
"        outline: none;\n"
"        transition: border-color 0.2s;\n"
"        background-color: var(--color-gray-700);\n"
"        color: var(--color-gray-200);\n"
"      }\n"
"      input[type=\"text\"]:focus,\n"
"      input[type=\"password\"]:focus {\n"
"        border-color: var(--color-primary);\n"
"      }\n"
"      .btn {\n"
"        width: 100%;\n"
"        padding: 0.75rem;\n"
"        border: none;\n"
"        border-radius: 0.5rem;\n"
"        font-size: 1rem;\n"
"        cursor: pointer;\n"
"        transition: opacity 0.2s;\n"
"      }\n"
"      .btn:disabled {\n"
"        opacity: 0.5;\n"
"        cursor: not-allowed;\n"
"      }\n"
"      .btn-primary {\n"
"        background-color: var(--color-primary);\n"
"        color: var(--color-white);\n"
"      }\n"
"      .btn-primary:hover:not(:disabled) {\n"
"        background-color: var(--color-primary-light);\n"
"      }\n"
"      .btn-secondary {\n"
"        background-color: var(--color-gray-500);\n"
"        color: var(--color-gray-200);\n"
"        margin-top: 0.5rem;\n"
"      }\n"
"      .btn:hover:not(:disabled) {\n"
"        opacity: 0.9;\n"
"      }\n"
"      .error {\n"
"        color: var(--color-error);\n"
"        font-size: 0.85rem;\n"
"        margin-top: 0.5rem;\n"
"        text-align: center;\n"
"      }\n"
"      .success {\n"
"        text-align: center;\n"
"        padding: 2rem 1rem;\n"
"      }\n"
"      .success h2 {\n"
"        color: var(--color-primary);\n"
"      }\n"
"      .success .claim-code {\n"
"        background: var(--color-gray-700);\n"
"        padding: 1rem;\n"
"        border-radius: 0.5rem;\n"
"        margin: 1rem 0;\n"
"      }\n"
"      .success .claim-code .code {\n"
"        font-size: 1.5rem;\n"
"        font-weight: bold;\n"
"        letter-spacing: 0.2rem;\n"
"        font-family: monospace;\n"
"        color: var(--color-gray-100);\n"
"      }\n"
"      .loading {\n"
"        display: inline-block;\n"
"        width: 1rem;\n"
"        height: 1rem;\n"
"        border: 2px solid var(--color-white);\n"
"        border-radius: 50%;\n"
"        border-top-color: transparent;\n"
"        animation: spin 0.8s linear infinite;\n"
"        margin-left: 0.5rem;\n"
"        vertical-align: middle;\n"
"      }\n"
"      @keyframes spin {\n"
"        to {\n"
"          transform: rotate(360deg);\n"
"        }\n"
"      }\n"
"      .refresh-btn {\n"
"        background: none;\n"
"        border: none;\n"
"        cursor: pointer;\n"
"        padding: 0.5rem;\n"
"        opacity: 0.6;\n"
"      }\n"
"      .refresh-btn:hover {\n"
"        opacity: 1;\n"
"      }\n"
"      .refresh-btn.spinning svg {\n"
"        animation: spin 0.5s linear infinite;\n"
"      }\n"
"      .hidden {\n"
"        display: none;\n"
"      }\n"
"      .footer {\n"
"        margin-top: 1.5rem;\n"
"        text-align: center;\n"
"      }\n"
"      .footer a {\n"
"        color: var(--color-gray-200);\n"
"        opacity: 0.5;\n"
"        font-size: 0.85rem;\n"
"        text-decoration: none;\n"
"      }\n"
"      .footer a:hover {\n"
"        opacity: 0.8;\n"
"      }\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"    <div class=\"card\" id=\"setup-card\">\n"
"      <h3>\n"
"        Connect to WiFi\n"
"        <button class=\"refresh-btn\" onclick=\"loadNetworks()\" title=\"Refresh\">\n"
"          <svg\n"
"            xmlns=\"http://www.w3.org/2000/svg\"\n"
"            width=\"18\"\n"
"            height=\"18\"\n"
"            viewBox=\"0 0 24 24\"\n"
"            fill=\"none\"\n"
"            stroke=\"currentColor\"\n"
"            stroke-width=\"2\"\n"
"          >\n"
"            <path d=\"M23 4v6h-6\"></path>\n"
"            <path d=\"M1 20v-6h6\"></path>\n"
"            <path\n"
"              d=\"M3.51 9a9 9 0 0 1 14.85-3.36L23 10M1 14l4.64 4.36A9 9 0 0 0 20.49 15\"\n"
"            ></path>\n"
"          </svg>\n"
"        </button>\n"
"      </h3>\n"
"\n"
"      <div class=\"network-list\" id=\"network-list\">\n"
"        <div style=\"padding: 2rem; text-align: center; opacity: 0.5\">\n"
"          Scanning for networks...\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <div class=\"form-group hidden\" id=\"hidden-ssid-group\">\n"
"        <label for=\"hidden-ssid\">Network Name (SSID)</label>\n"
"        <input type=\"text\" id=\"hidden-ssid\" placeholder=\"Enter network name\" />\n"
"      </div>\n"
"\n"
"      <div class=\"form-group hidden\" id=\"password-group\">\n"
"        <label for=\"password\">Password</label>\n"
"        <input type=\"password\" id=\"password\" placeholder=\"Enter password\" />\n"
"      </div>\n"
"\n"
"      <div class=\"error hidden\" id=\"error-msg\"></div>\n"
"\n"
"      <button\n"
"        class=\"btn btn-primary\"\n"
"        id=\"connect-btn\"\n"
"        onclick=\"connect()\"\n"
"        disabled\n"
"      >\n"
"        Connect\n"
"      </button>\n"
"\n"
"      <div class=\"footer\">\n"
"        <a href=\"#\" onclick=\"factoryReset(); return false;\">Factory Reset</a>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <div class=\"card hidden\" id=\"success-card\">\n"
"      <div class=\"success\">\n"
"        <svg\n"
"          xmlns=\"http://www.w3.org/2000/svg\"\n"
"          width=\"64\"\n"
"          height=\"64\"\n"
"          viewBox=\"0 0 24 24\"\n"
"          fill=\"none\"\n"
"          stroke=\"#b22222\"\n"
"          stroke-width=\"2\"\n"
"        >\n"
"          <circle cx=\"12\" cy=\"12\" r=\"10\"></circle>\n"
"          <polyline points=\"16 12 12 8 8 12\"></polyline>\n"
"          <line x1=\"12\" y1=\"16\" x2=\"12\" y2=\"8\"></line>\n"
"        </svg>\n"
"        <h2>Connected!</h2>\n"
"        <p id=\"connected-ssid\"></p>\n"
"        <div class=\"claim-code\">\n"
"          <div style=\"font-size: 0.85rem; opacity: 0.7; margin-bottom: 0.5rem\">\n"
"            Your claim code:\n"
"          </div>\n"
"          <div class=\"code\" id=\"claim-code\">--------</div>\n"
"          <div style=\"font-size: 0.8rem; opacity: 0.5; margin-top: 0.5rem\">\n"
"            Use this code to link your device\n"
"          </div>\n"
"        </div>\n"
"        <p style=\"opacity: 0.6; font-size: 0.9rem\">\n"
"          Your device is now provisioned and ready to use.\n"
"        </p>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <div class=\"card hidden\" id=\"reset-card\">\n"
"      <div style=\"text-align: center; padding: 1rem\">\n"
"        <h3>Factory Reset</h3>\n"
"        <p>Are you sure you want to reset the device to factory settings?</p>\n"
"        <p style=\"color: gray; font-size: 0.85rem\">\n"
"          This will erase all settings and streak data.\n"
"        </p>\n"
"        <div style=\"display: flex; gap: 1rem; margin-top: 1.5rem\">\n"
"          <button\n"
"            class=\"btn btn-secondary\"\n"
"            style=\"flex: 1\"\n"
"            onclick=\"cancelReset()\"\n"
"          >\n"
"            Cancel\n"
"          </button>\n"
"          <button\n"
"            class=\"btn btn-primary\"\n"
"            style=\"flex: 1; background-color: #cc0033\"\n"
"            onclick=\"confirmReset()\"\n"
"          >\n"
"            Reset\n"
"          </button>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <script>\n"
"      let selectedNetwork = null;\n"
"      let isHiddenNetwork = false;\n"
"\n"
"      window.addEventListener(\"load\", loadNetworks);\n"
"\n"
"      function loadNetworks() {\n"
"        const btn = document.querySelector(\".refresh-btn\");\n"
"        btn.classList.add(\"spinning\");\n"
"\n"
"        fetch(\"/api/scan\")\n"
"          .then((r) => r.json())\n"
"          .then((data) => {\n"
"            const list = document.getElementById(\"network-list\");\n"
"            if (data.networks && data.networks.length > 0) {\n"
"              list.innerHTML =\n"
"                data.networks\n"
"                  .map(\n"
"                    (n) => `\n"
"                <div class=\"network-item\" onclick=\"selectNetwork('${n.ssid}', ${\n"
"                      n.auth\n"
"                    })\">\n"
"                  <input type=\"radio\" name=\"network\" ${\n"
"                    selectedNetwork === n.ssid ? \"checked\" : \"\"\n"
"                  }>\n"
"                  <span class=\"network-name\">${n.ssid}</span>\n"
"                  <span class=\"network-signal\">${getSignalIcon(n.rssi)} ${\n"
"                      n.auth > 0 ? \"🔒\" : \"\"\n"
"                    }</span>\n"
"                </div>\n"
"              `\n"
"                  )\n"
"                  .join(\"\") +\n"
"                `\n"
"                <div class=\"network-item\" onclick=\"selectHidden()\">\n"
"                  <input type=\"radio\" name=\"network\" ${\n"
"                    isHiddenNetwork ? \"checked\" : \"\"\n"
"                  }>\n"
"                  <span class=\"network-name\" style=\"opacity: 0.7;\">Hidden Network...</span>\n"
"                </div>\n"
"              `;\n"
"            } else {\n"
"              list.innerHTML =\n"
"                '<div style=\"padding: 2rem; text-align: center; opacity: 0.5;\">No networks found. Click refresh to scan again.</div>';\n"
"            }\n"
"          })\n"
"          .catch((e) => {\n"
"            document.getElementById(\"network-list\").innerHTML =\n"
"              '<div style=\"padding: 2rem; text-align: center; color: #cc0033;\">Error scanning networks</div>';\n"
"          })\n"
"          .finally(() => btn.classList.remove(\"spinning\"));\n"
"      }\n"
"\n"
"      function getSignalIcon(rssi) {\n"
"        if (rssi >= -50) return \"▂▄▆█\";\n"
"        if (rssi >= -60) return \"▂▄▆░\";\n"
"        if (rssi >= -70) return \"▂▄░░\";\n"
"        return \"▂░░░\";\n"
"      }\n"
"\n"
"      function selectNetwork(ssid, auth) {\n"
"        selectedNetwork = ssid;\n"
"        isHiddenNetwork = false;\n"
"        document.getElementById(\"hidden-ssid-group\").classList.add(\"hidden\");\n"
"        document\n"
"          .getElementById(\"password-group\")\n"
"          .classList.toggle(\"hidden\", auth === 0);\n"
"        document.getElementById(\"connect-btn\").disabled = false;\n"
"        document.getElementById(\"error-msg\").classList.add(\"hidden\");\n"
"\n"
"        document\n"
"          .querySelectorAll(\".network-item\")\n"
"          .forEach((el) => el.classList.remove(\"selected\"));\n"
"        event.currentTarget.classList.add(\"selected\");\n"
"        event.currentTarget.querySelector(\"input\").checked = true;\n"
"      }\n"
"\n"
"      function selectHidden() {\n"
"        selectedNetwork = null;\n"
"        isHiddenNetwork = true;\n"
"        document.getElementById(\"hidden-ssid-group\").classList.remove(\"hidden\");\n"
"        document.getElementById(\"password-group\").classList.remove(\"hidden\");\n"
"        document.getElementById(\"connect-btn\").disabled = false;\n"
"        document.getElementById(\"error-msg\").classList.add(\"hidden\");\n"
"\n"
"        document\n"
"          .querySelectorAll(\".network-item\")\n"
"          .forEach((el) => el.classList.remove(\"selected\"));\n"
"        event.currentTarget.classList.add(\"selected\");\n"
"        event.currentTarget.querySelector(\"input\").checked = true;\n"
"      }\n"
"\n"
"      function connect() {\n"
"        const btn = document.getElementById(\"connect-btn\");\n"
"        const errorEl = document.getElementById(\"error-msg\");\n"
"        errorEl.classList.add(\"hidden\");\n"
"\n"
"        const ssid = isHiddenNetwork\n"
"          ? document.getElementById(\"hidden-ssid\").value\n"
"          : selectedNetwork;\n"
"        const password = document.getElementById(\"password\").value;\n"
"\n"
"        if (!ssid) {\n"
"          errorEl.textContent = \"Please select or enter a network\";\n"
"          errorEl.classList.remove(\"hidden\");\n"
"          return;\n"
"        }\n"
"\n"
"        btn.disabled = true;\n"
"        btn.innerHTML = 'Connecting<span class=\"loading\"></span>';\n"
"\n"
"        fetch(\"/api/connect\", {\n"
"          method: \"POST\",\n"
"          headers: { \"Content-Type\": \"application/json\" },\n"
"          body: JSON.stringify({ ssid, password }),\n"
"        })\n"
"          .then((r) => r.json())\n"
"          .then((data) => {\n"
"            if (data.success) {\n"
"              document.getElementById(\"setup-card\").classList.add(\"hidden\");\n"
"              document\n"
"                .getElementById(\"success-card\")\n"
"                .classList.remove(\"hidden\");\n"
"              document.getElementById(\"connected-ssid\").textContent =\n"
"                \"Connected to \" + ssid;\n"
"              document.getElementById(\"claim-code\").textContent =\n"
"                data.claim_code || \"N/A\";\n"
"            } else {\n"
"              errorEl.textContent = data.error || \"Failed to connect\";\n"
"              errorEl.classList.remove(\"hidden\");\n"
"              btn.disabled = false;\n"
"              btn.textContent = \"Connect\";\n"
"            }\n"
"          })\n"
"          .catch((e) => {\n"
"            errorEl.textContent = \"Connection error. Please try again.\";\n"
"            errorEl.classList.remove(\"hidden\");\n"
"            btn.disabled = false;\n"
"            btn.textContent = \"Connect\";\n"
"          });\n"
"      }\n"
"\n"
"      function factoryReset() {\n"
"        document.getElementById(\"setup-card\").classList.add(\"hidden\");\n"
"        document.getElementById(\"reset-card\").classList.remove(\"hidden\");\n"
"      }\n"
"\n"
"      function cancelReset() {\n"
"        document.getElementById(\"reset-card\").classList.add(\"hidden\");\n"
"        document.getElementById(\"setup-card\").classList.remove(\"hidden\");\n"
"      }\n"
"\n"
"      function confirmReset() {\n"
"        fetch(\"/api/reset\", { method: \"POST\" })\n"
"          .then(() => {\n"
"            document.getElementById(\"reset-card\").innerHTML =\n"
"              '<div style=\"text-align: center; padding: 2rem;\"><h3 style=\"color: #b22222;\">Reset Complete</h3><p>Device will restart...</p></div>';\n"
"            setTimeout(() => location.reload(), 3000);\n"
"          })\n"
"          .catch(() => {\n"
"            alert(\"Reset failed. Please try again.\");\n"
"          });\n"
"      }\n"
"    </script>\n"
"  </body>\n"
"</html>\n"
"";

#define CAPTIVE_PORTAL_HTML_LEN (sizeof(CAPTIVE_PORTAL_HTML) - 1)

#endif // CAPTIVE_PORTAL_H
